Script started on Wed 04 Nov 2015 12:30:46 PM PST
[asong011@hammer rshell]$ bin/rshell


rShell [Version 20151103 exec]

Use "verbose [on|off]" to toggle verbose output.


[asong011@hammer.cs.ucr.edu] R$ bin/rshell #Starting the second rshell


rShell [Version 20151103 exec]

Use "verbose [on|off]" to toggle verbose output.


[asong011@hammer.cs.ucr.edu] R$ bin/rshell #starting the third rshell


rShell [Version 20151103 exec]

Use "verbose [on|off]" to toggle verbose output.


[asong011@hammer.cs.ucr.edu] R$ ls
bin  commented_command.script  LICENSE	Makefile  multi_commands.script	 README.md  record  single_command.script  src	tests

[asong011@hammer.cs.ucr.edu] R$ exit #exit the third rshell

[asong011@hammer.cs.ucr.edu] R$ echo 2
2

[asong011@hammer.cs.ucr.edu] R$ exit #exit the 2nd rshell

[asong011@hammer.cs.ucr.edu] R$ echo 1
1

[asong011@hammer.cs.ucr.edu] R$ exit #this will quit rshell
[asong011@hammer rshell]$ exit
exit

Script done on Wed 04 Nov 2015 12:32:13 PM PST
