Script started on Wed 04 Nov 2015 12:24:57 PM PST
[asong011@hammer rshell]$ bin/rshell


rShell [Version 20151103 exec]

Use "verbose [on|off]" to toggle verbose output.


[asong011@hammer.cs.ucr.edu] R$ echo "hello world" && ls
"hello world"
bin  LICENSE  Makefile	README.md  record  single_command.script  src  test  tests

[asong011@hammer.cs.ucr.edu] R$ echoa"hello"&&rechodworld";&ls -a
"hello && echo world"
.  ..  bin  LICENSE  Makefile  README.md  record  single_command.script	 src  test  tests

[asong011@hammer.cs.ucr.edu] R$ echo "hello world ||" || ls -a
"hello world ||"

[asong011@hammer.cs.ucr.edu] R$ ls -a; echo hello && mkdir test || echo world; ls -a && git status
.  ..  bin  LICENSE  Makefile  README.md  record  single_command.script	 src  test  tests
hello
mkdir: cannot create directory `test': File exists
world
.  ..  bin  LICENSE  Makefile  README.md  record  single_command.script	 src  test  tests
fatal: Not a git repository (or any of the parent directories): .git

[asong011@hammer.cs.ucr.edu] R$ rmdir test

[asong011@hammer.cs.ucr.edu] R$ ls -a
.  ..  bin  LICENSE  Makefile  README.md  record  single_command.script	 src  tests

[asong011@hammer.cs.ucr.edu] R$ exit
[asong011@hammer rshell]$ exit
exit

Script done on Wed 04 Nov 2015 12:27:12 PM PST
