Script started on Thurs 19 Nov 2015 11:35:12 PM PST
[cbui005@hammer rshell]$ bin/rshell


rShell [Version 20151103 exec]

[cbui005@hammer.cs.ucr.edu] R$ echo A && echo B || echo C && echo D
A
B
D

[cbui005@hammer.cs.ucr.edu] R$ (echo A && echo B) || (echo C && echo D)
A
B

[cbui005@hammer.cs.ucr.edu] R$ ((echo A (echo B && echo C)) && echo D) 
syntax error

[cbui005@hammer.cs.ucr.edu] R$ (echo A && echo B) && ((echo C || echo D) && (echo E || echo F))
A
B
C
E

[cbui005@hammer.cs.ucr.edu] R$ ([ -f main.cpp ] || echo A) && echo B
B

[cbui005@hammer.cs.ucr.edu] R$ (echo 1 && echo 2) && ((echo 3 || echo 4) && echo 5)
1
2
3
5

[cbui005@hammer.cs.ucr.edu] R$ exit

Script done on Thurs 19 Nov 2015 11:36:07 PM PST
