Script started on Wed 04 Nov 2015 12:14:19 PM PST
[asong011@hammer rshell]$ bin/rshelll


rShell [Version 20151103 exec]

Use "verbose [on|off]" to toggle verbose output.


[asong011@hammer.cs.ucr.edu] R$ ls
bin  LICENSE  Makefile	README.md  single_command.script  src  tests

[asong011@hammer.cs.ucr.edu] R$ ls -a
.  ..  bin  LICENSE  Makefile  README.md  single_command.script	 src  tests

[asong011@hammer.cs.ucr.edu] R$ ls -l
total 40
drwxr-xr-x 2 asong011 csmajs  4096 Nov	4 12:11 bin
-rw-r--r-- 1 asong011 csmajs 18047 Oct 24 12:54 LICENSE
-rw-r--r-- 1 asong011 csmajs   198 Oct 28 22:49 Makefile
-rw-r--r-- 1 asong011 csmajs	 9 Oct 24 12:54 README.md
-rw-r--r-- 1 asong011 csmajs	 0 Nov	4 12:14 single_command.script
drwxr-xr-x 2 asong011 csmajs  4096 Nov	4 11:33 src
drwxr-xr-x 2 asong011 csmajs  4096 Nov	4 12:10 tests

[asong011@hammer.cs.ucr.edu] R$ echo hello
hello

[asong011@hammer.cs.ucr.edu] R$ echo hello world
hello world

[asong011@hammer.cs.ucr.edu] R$ echo "hello world"
"hello world"

[asong011@hammer.cs.ucr.edu] R$ git status
fatal: Not a git repository (or any of the parent directories): .git

[asong011@hammer.cs.ucr.edu] R$ mkdir 11111

[asong011@hammer.cs.ucr.edu] R$ ls
11111  bin  LICENSE  Makefile  README.md  single_command.script	 src  tests

[asong011@hammer.cs.ucr.edu] R$ rmdir 11111

[asong011@hammer.cs.ucr.edu] R$ ls
bin  LICENSE  Makefile	README.md  single_command.script  src  tests

[asong011@hammer.cs.ucr.edu] R$ exit
[asong011@hammer rshell]$ exit
exit

Script done on Wed 04 Nov 2015 12:15:07 PM PST
