Script started on Thurs 19 Nov 2015 11:38:12 PM PST
[cbui005@hammer rshell]$ bin/rshell


rShell [Version 20151119 cmdHistory & Pipe]

[cbui005@hammer.cs.ucr.edu] R$ test -e src && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -f src && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ test -d src && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -e main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -f main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -d main.cpp && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ test main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -ef main.cpp && echo "exists"
bash: test: Invalid flag: -ef

[cbui005@hammer.cs.ucr.edu] R$ test "-f" main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test "-d" main.cpp && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ "test" -e main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ [ -e main.cpp ] && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ [ -f main.cpp ] && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ [ -d main.cpp ] && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ [-e main.cpp ] && echo "exists"
bash: [-e: command not found

[cbui005@hammer.cs.ucr.edu] R$ [ "-e main.cpp" ] && echo "exists"
Invalid flag: -e main.cpp

[cbui005@hammer.cs.ucr.edu] R$ [[ "-e main.cpp" ]] && echo "exists"
exec failed: No such file or directory

[cbui005@hammer.cs.ucr.edu] R$ [ -e main.cpp# ] && echo "exists"
[: missing ']'

[cbui005@hammer.cs.ucr.edu] R$ [ main.cpp ] $$ echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ [ [test] ] $$ echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ exit

Script done on Thurs 19 Nov 2015 11:39:02 PM PST
