Script started on Thurs 19 Nov 2015 11:38:12 PM PST
[cbui005@hammer rshell]$ bin/rshell


rShell [Version 20151103 exec]

[cbui005@hammer.cs.ucr.edu] R$ test -e src && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -f src && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ test -d src && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -e main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -f main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -d main.cpp && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ test main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test -ef main.cpp && echo "exists"
bash: test: Invalid flag: -ef

[cbui005@hammer.cs.ucr.edu] R$ test "-f" main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ test "-d" main.cpp && echo "exists"

[cbui005@hammer.cs.ucr.edu] R$ "test" -e main.cpp && echo "exists"
exists

[cbui005@hammer.cs.ucr.edu] R$ exit

Script done on Thurs 19 Nov 2015 11:39:02 PM PST